kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: docker:stable-dind
    volumes:
      - name: docker_run
        path: /var/run/
      - name: docker_lib
        path:  /var/lib/docker
    commands:
      - docker build --no-cache --target syncjob -t yeyus/dmr-entities-syncjob:latest .
      - docker build --no-cache --target server -t yeyus/dmr-entities-server:latest .
