// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entities.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	entities.proto

It has these top-level messages:
	EntitiesQuery
	EntitiesResponse
	Pagination
	Entity
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Namespace int32

const (
	Namespace_UNKNOWN_NAMESPACE Namespace = 0
	Namespace_RADIOID           Namespace = 1
	Namespace_DMRMARC           Namespace = 2
	Namespace_BRANDMEISTER      Namespace = 3
	Namespace_TGIF              Namespace = 4
)

var Namespace_name = map[int32]string{
	0: "UNKNOWN_NAMESPACE",
	1: "RADIOID",
	2: "DMRMARC",
	3: "BRANDMEISTER",
	4: "TGIF",
}
var Namespace_value = map[string]int32{
	"UNKNOWN_NAMESPACE": 0,
	"RADIOID":           1,
	"DMRMARC":           2,
	"BRANDMEISTER":      3,
	"TGIF":              4,
}

func (x Namespace) String() string {
	return proto.EnumName(Namespace_name, int32(x))
}
func (Namespace) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SystemType int32

const (
	SystemType_UNKNOWN_SYSTEM_TYPE SystemType = 0
	SystemType_DMR                 SystemType = 1
	SystemType_NXDN                SystemType = 2
)

var SystemType_name = map[int32]string{
	0: "UNKNOWN_SYSTEM_TYPE",
	1: "DMR",
	2: "NXDN",
}
var SystemType_value = map[string]int32{
	"UNKNOWN_SYSTEM_TYPE": 0,
	"DMR":  1,
	"NXDN": 2,
}

func (x SystemType) String() string {
	return proto.EnumName(SystemType_name, int32(x))
}
func (SystemType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type EntityType int32

const (
	EntityType_UNKNOWN_ENTITY_TYPE EntityType = 0
	EntityType_HAM                 EntityType = 1
	EntityType_TALKGROUP           EntityType = 2
)

var EntityType_name = map[int32]string{
	0: "UNKNOWN_ENTITY_TYPE",
	1: "HAM",
	2: "TALKGROUP",
}
var EntityType_value = map[string]int32{
	"UNKNOWN_ENTITY_TYPE": 0,
	"HAM":       1,
	"TALKGROUP": 2,
}

func (x EntityType) String() string {
	return proto.EnumName(EntityType_name, int32(x))
}
func (EntityType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type EntitiesQuery struct {
	Query      string     `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	CountryIso string     `protobuf:"bytes,2,opt,name=country_iso,json=countryIso" json:"country_iso,omitempty"`
	Type       EntityType `protobuf:"varint,3,opt,name=type,enum=api.EntityType" json:"type,omitempty"`
	System     SystemType `protobuf:"varint,4,opt,name=system,enum=api.SystemType" json:"system,omitempty"`
	Namespace  Namespace  `protobuf:"varint,7,opt,name=namespace,enum=api.Namespace" json:"namespace,omitempty"`
	PageSize   uint32     `protobuf:"varint,5,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageStart  uint32     `protobuf:"varint,6,opt,name=page_start,json=pageStart" json:"page_start,omitempty"`
}

func (m *EntitiesQuery) Reset()                    { *m = EntitiesQuery{} }
func (m *EntitiesQuery) String() string            { return proto.CompactTextString(m) }
func (*EntitiesQuery) ProtoMessage()               {}
func (*EntitiesQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EntitiesQuery) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *EntitiesQuery) GetCountryIso() string {
	if m != nil {
		return m.CountryIso
	}
	return ""
}

func (m *EntitiesQuery) GetType() EntityType {
	if m != nil {
		return m.Type
	}
	return EntityType_UNKNOWN_ENTITY_TYPE
}

func (m *EntitiesQuery) GetSystem() SystemType {
	if m != nil {
		return m.System
	}
	return SystemType_UNKNOWN_SYSTEM_TYPE
}

func (m *EntitiesQuery) GetNamespace() Namespace {
	if m != nil {
		return m.Namespace
	}
	return Namespace_UNKNOWN_NAMESPACE
}

func (m *EntitiesQuery) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *EntitiesQuery) GetPageStart() uint32 {
	if m != nil {
		return m.PageStart
	}
	return 0
}

type EntitiesResponse struct {
	Entities   []*Entity   `protobuf:"bytes,1,rep,name=entities" json:"entities,omitempty"`
	Pagination *Pagination `protobuf:"bytes,2,opt,name=pagination" json:"pagination,omitempty"`
}

func (m *EntitiesResponse) Reset()                    { *m = EntitiesResponse{} }
func (m *EntitiesResponse) String() string            { return proto.CompactTextString(m) }
func (*EntitiesResponse) ProtoMessage()               {}
func (*EntitiesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EntitiesResponse) GetEntities() []*Entity {
	if m != nil {
		return m.Entities
	}
	return nil
}

func (m *EntitiesResponse) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type Pagination struct {
	Total     uint32 `protobuf:"varint,1,opt,name=total" json:"total,omitempty"`
	PageStart uint32 `protobuf:"varint,2,opt,name=page_start,json=pageStart" json:"page_start,omitempty"`
	PageSize  uint32 `protobuf:"varint,3,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
}

func (m *Pagination) Reset()                    { *m = Pagination{} }
func (m *Pagination) String() string            { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()               {}
func (*Pagination) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Pagination) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Pagination) GetPageStart() uint32 {
	if m != nil {
		return m.PageStart
	}
	return 0
}

func (m *Pagination) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type Entity struct {
	Id         uint64     `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	SystemId   uint64     `protobuf:"varint,2,opt,name=system_id,json=systemId" json:"system_id,omitempty"`
	System     SystemType `protobuf:"varint,3,opt,name=system,enum=api.SystemType" json:"system,omitempty"`
	Type       EntityType `protobuf:"varint,4,opt,name=type,enum=api.EntityType" json:"type,omitempty"`
	Namespace  Namespace  `protobuf:"varint,5,opt,name=namespace,enum=api.Namespace" json:"namespace,omitempty"`
	Callsign   string     `protobuf:"bytes,6,opt,name=callsign" json:"callsign,omitempty"`
	Name       string     `protobuf:"bytes,7,opt,name=name" json:"name,omitempty"`
	Surname    string     `protobuf:"bytes,8,opt,name=surname" json:"surname,omitempty"`
	Country    string     `protobuf:"bytes,9,opt,name=country" json:"country,omitempty"`
	CountryIso string     `protobuf:"bytes,10,opt,name=country_iso,json=countryIso" json:"country_iso,omitempty"`
	State      string     `protobuf:"bytes,11,opt,name=state" json:"state,omitempty"`
	City       string     `protobuf:"bytes,12,opt,name=city" json:"city,omitempty"`
}

func (m *Entity) Reset()                    { *m = Entity{} }
func (m *Entity) String() string            { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()               {}
func (*Entity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Entity) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Entity) GetSystemId() uint64 {
	if m != nil {
		return m.SystemId
	}
	return 0
}

func (m *Entity) GetSystem() SystemType {
	if m != nil {
		return m.System
	}
	return SystemType_UNKNOWN_SYSTEM_TYPE
}

func (m *Entity) GetType() EntityType {
	if m != nil {
		return m.Type
	}
	return EntityType_UNKNOWN_ENTITY_TYPE
}

func (m *Entity) GetNamespace() Namespace {
	if m != nil {
		return m.Namespace
	}
	return Namespace_UNKNOWN_NAMESPACE
}

func (m *Entity) GetCallsign() string {
	if m != nil {
		return m.Callsign
	}
	return ""
}

func (m *Entity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Entity) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *Entity) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Entity) GetCountryIso() string {
	if m != nil {
		return m.CountryIso
	}
	return ""
}

func (m *Entity) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Entity) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func init() {
	proto.RegisterType((*EntitiesQuery)(nil), "api.EntitiesQuery")
	proto.RegisterType((*EntitiesResponse)(nil), "api.EntitiesResponse")
	proto.RegisterType((*Pagination)(nil), "api.Pagination")
	proto.RegisterType((*Entity)(nil), "api.Entity")
	proto.RegisterEnum("api.Namespace", Namespace_name, Namespace_value)
	proto.RegisterEnum("api.SystemType", SystemType_name, SystemType_value)
	proto.RegisterEnum("api.EntityType", EntityType_name, EntityType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Entities service

type EntitiesClient interface {
	GetEntity(ctx context.Context, in *EntitiesQuery, opts ...grpc.CallOption) (*EntitiesResponse, error)
}

type entitiesClient struct {
	cc *grpc.ClientConn
}

func NewEntitiesClient(cc *grpc.ClientConn) EntitiesClient {
	return &entitiesClient{cc}
}

func (c *entitiesClient) GetEntity(ctx context.Context, in *EntitiesQuery, opts ...grpc.CallOption) (*EntitiesResponse, error) {
	out := new(EntitiesResponse)
	err := grpc.Invoke(ctx, "/api.Entities/GetEntity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Entities service

type EntitiesServer interface {
	GetEntity(context.Context, *EntitiesQuery) (*EntitiesResponse, error)
}

func RegisterEntitiesServer(s *grpc.Server, srv EntitiesServer) {
	s.RegisterService(&_Entities_serviceDesc, srv)
}

func _Entities_GetEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntitiesQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitiesServer).GetEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Entities/GetEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitiesServer).GetEntity(ctx, req.(*EntitiesQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _Entities_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Entities",
	HandlerType: (*EntitiesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEntity",
			Handler:    _Entities_GetEntity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "entities.proto",
}

func init() { proto.RegisterFile("entities.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 584 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0xad, 0xff, 0x24, 0xb1, 0x27, 0x4d, 0x7e, 0xfe, 0x2d, 0xad, 0x58, 0x15, 0x21, 0xa2, 0x70,
	0x20, 0xaa, 0x50, 0x91, 0xca, 0xa5, 0x17, 0x0e, 0xa6, 0x36, 0xc5, 0x2a, 0x76, 0xc3, 0xda, 0x15,
	0xed, 0x85, 0xc8, 0x24, 0xab, 0x6a, 0xa5, 0xd4, 0x36, 0xd9, 0xed, 0xc1, 0xfd, 0xb4, 0x7c, 0x12,
	0x84, 0x76, 0x6d, 0x27, 0x4e, 0x90, 0xca, 0x6d, 0xe7, 0xbd, 0xb7, 0xe3, 0x99, 0x79, 0xe3, 0x85,
	0x21, 0xcd, 0x04, 0x13, 0x8c, 0xf2, 0x93, 0x62, 0x95, 0x8b, 0x1c, 0x19, 0x69, 0xc1, 0xc6, 0xbf,
	0x35, 0x18, 0xf8, 0x35, 0xfe, 0xf5, 0x81, 0xae, 0x4a, 0x74, 0x00, 0x9d, 0x9f, 0xf2, 0x80, 0xb5,
	0x91, 0x36, 0xb1, 0x49, 0x15, 0xa0, 0x57, 0xd0, 0x9f, 0xe7, 0x0f, 0x99, 0x58, 0x95, 0x33, 0xc6,
	0x73, 0xac, 0x2b, 0x0e, 0x6a, 0x28, 0xe0, 0x39, 0x7a, 0x0d, 0xa6, 0x28, 0x0b, 0x8a, 0x8d, 0x91,
	0x36, 0x19, 0x9e, 0xfe, 0x77, 0x92, 0x16, 0xec, 0x44, 0x25, 0x2e, 0x93, 0xb2, 0xa0, 0x44, 0x91,
	0xe8, 0x0d, 0x74, 0x79, 0xc9, 0x05, 0xbd, 0xc7, 0x66, 0x4b, 0x16, 0x2b, 0x48, 0xc9, 0x6a, 0x1a,
	0xbd, 0x05, 0x3b, 0x4b, 0xef, 0x29, 0x2f, 0xd2, 0x39, 0xc5, 0x3d, 0xa5, 0x1d, 0x2a, 0x6d, 0xd4,
	0xa0, 0x64, 0x23, 0x40, 0x2f, 0xc0, 0x2e, 0xd2, 0x3b, 0x3a, 0xe3, 0xec, 0x91, 0xe2, 0xce, 0x48,
	0x9b, 0x0c, 0x88, 0x25, 0x81, 0x98, 0x3d, 0x52, 0xf4, 0x12, 0xa0, 0x22, 0x45, 0xba, 0x12, 0xb8,
	0xab, 0x58, 0x25, 0x8f, 0x25, 0x30, 0x5e, 0x82, 0xd3, 0xf4, 0x4f, 0x28, 0x2f, 0xf2, 0x8c, 0xcb,
	0x32, 0xad, 0x66, 0x56, 0x58, 0x1b, 0x19, 0x93, 0xfe, 0x69, 0xbf, 0xd5, 0x0f, 0x59, 0x93, 0xe8,
	0x9d, 0xca, 0xcd, 0xb2, 0x54, 0xb0, 0x3c, 0x53, 0x43, 0xe9, 0xd7, 0x3d, 0x4d, 0xd7, 0x30, 0x69,
	0x49, 0xc6, 0xdf, 0x01, 0x36, 0x8c, 0x1c, 0xb5, 0xc8, 0x45, 0xba, 0x54, 0xa3, 0x1e, 0x90, 0x2a,
	0xd8, 0x29, 0x58, 0xdf, 0x29, 0x78, 0xbb, 0x59, 0x63, 0xbb, 0xd9, 0xf1, 0x2f, 0x1d, 0xba, 0x55,
	0x95, 0x68, 0x08, 0x3a, 0x5b, 0xa8, 0xcc, 0x26, 0xd1, 0xd9, 0x42, 0xde, 0xab, 0x86, 0x3b, 0x63,
	0x0b, 0x95, 0xd5, 0x24, 0x56, 0x05, 0x04, 0x8b, 0x96, 0x31, 0xc6, 0xd3, 0xc6, 0x34, 0x36, 0x9b,
	0x4f, 0xd9, 0xbc, 0xe5, 0x5e, 0xe7, 0x5f, 0xee, 0x1d, 0x81, 0x35, 0x4f, 0x97, 0x4b, 0xce, 0xee,
	0x32, 0x65, 0x8f, 0x4d, 0xd6, 0x31, 0x42, 0x60, 0x4a, 0xa1, 0x5a, 0x01, 0x9b, 0xa8, 0x33, 0xc2,
	0xd0, 0xe3, 0x0f, 0x2b, 0x05, 0x5b, 0x0a, 0x6e, 0x42, 0xc9, 0xd4, 0x1b, 0x89, 0xed, 0x8a, 0xa9,
	0xc3, 0xdd, 0xf5, 0x85, 0xbf, 0xd6, 0xf7, 0x00, 0x3a, 0x5c, 0xa4, 0x82, 0xe2, 0x7e, 0xb5, 0xf5,
	0x2a, 0x90, 0x9f, 0x9f, 0x33, 0x51, 0xe2, 0xfd, 0xea, 0xf3, 0xf2, 0x7c, 0x7c, 0x03, 0xf6, 0xba,
	0x0d, 0x74, 0x08, 0xff, 0x5f, 0x47, 0x97, 0xd1, 0xd5, 0xb7, 0x68, 0x16, 0xb9, 0xa1, 0x1f, 0x4f,
	0xdd, 0x73, 0xdf, 0xd9, 0x43, 0x7d, 0xe8, 0x11, 0xd7, 0x0b, 0xae, 0x02, 0xcf, 0xd1, 0x64, 0xe0,
	0x85, 0x24, 0x74, 0xc9, 0xb9, 0xa3, 0x23, 0x07, 0xf6, 0x3f, 0x12, 0x37, 0xf2, 0x42, 0x3f, 0x88,
	0x13, 0x9f, 0x38, 0x06, 0xb2, 0xc0, 0x4c, 0x2e, 0x82, 0x4f, 0x8e, 0x79, 0x7c, 0x06, 0xb0, 0x99,
	0x38, 0x7a, 0x0e, 0xcf, 0x9a, 0xd4, 0xf1, 0x6d, 0x9c, 0xf8, 0xe1, 0x2c, 0xb9, 0x9d, 0xca, 0xe4,
	0x3d, 0x30, 0xbc, 0x90, 0x38, 0x9a, 0xbc, 0x19, 0xdd, 0x78, 0x91, 0xa3, 0x1f, 0x7f, 0x00, 0xd8,
	0x98, 0xd0, 0xbe, 0xe9, 0x47, 0x49, 0x90, 0xdc, 0xb6, 0x6e, 0x7e, 0x76, 0x43, 0x47, 0x43, 0x03,
	0xb0, 0x13, 0xf7, 0xcb, 0xe5, 0x05, 0xb9, 0xba, 0x9e, 0x3a, 0xfa, 0xa9, 0x07, 0x56, 0xf3, 0x0f,
	0xa0, 0x33, 0xb0, 0x2f, 0xa8, 0xa8, 0x77, 0x08, 0x6d, 0xfc, 0x6d, 0xde, 0x87, 0xa3, 0xc3, 0x2d,
	0xac, 0xf9, 0x67, 0xc6, 0x7b, 0x3f, 0xba, 0xea, 0x59, 0x79, 0xff, 0x27, 0x00, 0x00, 0xff, 0xff,
	0xed, 0x78, 0xd9, 0xe8, 0x68, 0x04, 0x00, 0x00,
}
