// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entities.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	entities.proto

It has these top-level messages:
	EntitiesQuery
	EntitiesResponse
	Meta
	Entity
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SystemType int32

const (
	SystemType_UNKNOWN_SYSTEM_TYPE SystemType = 0
	SystemType_DMR                 SystemType = 1
)

var SystemType_name = map[int32]string{
	0: "UNKNOWN_SYSTEM_TYPE",
	1: "DMR",
}
var SystemType_value = map[string]int32{
	"UNKNOWN_SYSTEM_TYPE": 0,
	"DMR": 1,
}

func (x SystemType) String() string {
	return proto.EnumName(SystemType_name, int32(x))
}
func (SystemType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EntityType int32

const (
	EntityType_UNKNOWN_ENTITY_TYPE EntityType = 0
	EntityType_HAM                 EntityType = 1
	EntityType_TALKGROUP           EntityType = 2
)

var EntityType_name = map[int32]string{
	0: "UNKNOWN_ENTITY_TYPE",
	1: "HAM",
	2: "TALKGROUP",
}
var EntityType_value = map[string]int32{
	"UNKNOWN_ENTITY_TYPE": 0,
	"HAM":       1,
	"TALKGROUP": 2,
}

func (x EntityType) String() string {
	return proto.EnumName(EntityType_name, int32(x))
}
func (EntityType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type EntitiesQuery struct {
	Query      string     `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	CountryIso string     `protobuf:"bytes,2,opt,name=country_iso,json=countryIso" json:"country_iso,omitempty"`
	Type       EntityType `protobuf:"varint,3,opt,name=type,enum=api.EntityType" json:"type,omitempty"`
	System     SystemType `protobuf:"varint,4,opt,name=system,enum=api.SystemType" json:"system,omitempty"`
	PageSize   uint32     `protobuf:"varint,5,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageStart  uint32     `protobuf:"varint,6,opt,name=page_start,json=pageStart" json:"page_start,omitempty"`
}

func (m *EntitiesQuery) Reset()                    { *m = EntitiesQuery{} }
func (m *EntitiesQuery) String() string            { return proto.CompactTextString(m) }
func (*EntitiesQuery) ProtoMessage()               {}
func (*EntitiesQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EntitiesQuery) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *EntitiesQuery) GetCountryIso() string {
	if m != nil {
		return m.CountryIso
	}
	return ""
}

func (m *EntitiesQuery) GetType() EntityType {
	if m != nil {
		return m.Type
	}
	return EntityType_UNKNOWN_ENTITY_TYPE
}

func (m *EntitiesQuery) GetSystem() SystemType {
	if m != nil {
		return m.System
	}
	return SystemType_UNKNOWN_SYSTEM_TYPE
}

func (m *EntitiesQuery) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *EntitiesQuery) GetPageStart() uint32 {
	if m != nil {
		return m.PageStart
	}
	return 0
}

type EntitiesResponse struct {
	Entities []*Entity `protobuf:"bytes,1,rep,name=entities" json:"entities,omitempty"`
	Meta     *Meta     `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
}

func (m *EntitiesResponse) Reset()                    { *m = EntitiesResponse{} }
func (m *EntitiesResponse) String() string            { return proto.CompactTextString(m) }
func (*EntitiesResponse) ProtoMessage()               {}
func (*EntitiesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EntitiesResponse) GetEntities() []*Entity {
	if m != nil {
		return m.Entities
	}
	return nil
}

func (m *EntitiesResponse) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type Meta struct {
	Total     uint32 `protobuf:"varint,1,opt,name=total" json:"total,omitempty"`
	PageStart uint32 `protobuf:"varint,2,opt,name=page_start,json=pageStart" json:"page_start,omitempty"`
	PageSize  uint32 `protobuf:"varint,3,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
}

func (m *Meta) Reset()                    { *m = Meta{} }
func (m *Meta) String() string            { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()               {}
func (*Meta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Meta) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Meta) GetPageStart() uint32 {
	if m != nil {
		return m.PageStart
	}
	return 0
}

func (m *Meta) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type Entity struct {
	Id         uint32     `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	System     SystemType `protobuf:"varint,2,opt,name=system,enum=api.SystemType" json:"system,omitempty"`
	Type       EntityType `protobuf:"varint,3,opt,name=type,enum=api.EntityType" json:"type,omitempty"`
	Callsign   string     `protobuf:"bytes,4,opt,name=callsign" json:"callsign,omitempty"`
	Name       string     `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	Surname    string     `protobuf:"bytes,6,opt,name=surname" json:"surname,omitempty"`
	Country    string     `protobuf:"bytes,7,opt,name=country" json:"country,omitempty"`
	CountryIso string     `protobuf:"bytes,8,opt,name=country_iso,json=countryIso" json:"country_iso,omitempty"`
	State      string     `protobuf:"bytes,9,opt,name=state" json:"state,omitempty"`
	City       string     `protobuf:"bytes,10,opt,name=city" json:"city,omitempty"`
}

func (m *Entity) Reset()                    { *m = Entity{} }
func (m *Entity) String() string            { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()               {}
func (*Entity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Entity) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Entity) GetSystem() SystemType {
	if m != nil {
		return m.System
	}
	return SystemType_UNKNOWN_SYSTEM_TYPE
}

func (m *Entity) GetType() EntityType {
	if m != nil {
		return m.Type
	}
	return EntityType_UNKNOWN_ENTITY_TYPE
}

func (m *Entity) GetCallsign() string {
	if m != nil {
		return m.Callsign
	}
	return ""
}

func (m *Entity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Entity) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *Entity) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Entity) GetCountryIso() string {
	if m != nil {
		return m.CountryIso
	}
	return ""
}

func (m *Entity) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Entity) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func init() {
	proto.RegisterType((*EntitiesQuery)(nil), "api.EntitiesQuery")
	proto.RegisterType((*EntitiesResponse)(nil), "api.EntitiesResponse")
	proto.RegisterType((*Meta)(nil), "api.Meta")
	proto.RegisterType((*Entity)(nil), "api.Entity")
	proto.RegisterEnum("api.SystemType", SystemType_name, SystemType_value)
	proto.RegisterEnum("api.EntityType", EntityType_name, EntityType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Entities service

type EntitiesClient interface {
	GetEntity(ctx context.Context, in *EntitiesQuery, opts ...grpc.CallOption) (*EntitiesResponse, error)
}

type entitiesClient struct {
	cc *grpc.ClientConn
}

func NewEntitiesClient(cc *grpc.ClientConn) EntitiesClient {
	return &entitiesClient{cc}
}

func (c *entitiesClient) GetEntity(ctx context.Context, in *EntitiesQuery, opts ...grpc.CallOption) (*EntitiesResponse, error) {
	out := new(EntitiesResponse)
	err := grpc.Invoke(ctx, "/api.Entities/GetEntity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Entities service

type EntitiesServer interface {
	GetEntity(context.Context, *EntitiesQuery) (*EntitiesResponse, error)
}

func RegisterEntitiesServer(s *grpc.Server, srv EntitiesServer) {
	s.RegisterService(&_Entities_serviceDesc, srv)
}

func _Entities_GetEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntitiesQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitiesServer).GetEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Entities/GetEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitiesServer).GetEntity(ctx, req.(*EntitiesQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _Entities_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Entities",
	HandlerType: (*EntitiesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEntity",
			Handler:    _Entities_GetEntity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "entities.proto",
}

func init() { proto.RegisterFile("entities.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 471 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x3f, 0xe2, 0xd8, 0x13, 0x25, 0x58, 0x4b, 0x11, 0xab, 0xa2, 0x8a, 0xc8, 0x1c, 0x88,
	0x7a, 0xc8, 0x21, 0x5c, 0xb8, 0x70, 0xa8, 0xd4, 0xa8, 0x54, 0x25, 0x69, 0x59, 0xbb, 0x82, 0x70,
	0x89, 0x96, 0x74, 0x55, 0xad, 0x94, 0xd8, 0xc6, 0xbb, 0x39, 0xb8, 0xff, 0x83, 0xff, 0xc5, 0x4f,
	0x42, 0x3b, 0xb6, 0x1b, 0x27, 0x48, 0xa8, 0xb7, 0x7d, 0xef, 0x8d, 0x76, 0xe7, 0xcd, 0xbc, 0x85,
	0x81, 0x48, 0xb5, 0xd4, 0x52, 0xa8, 0x71, 0x5e, 0x64, 0x3a, 0x23, 0x0e, 0xcf, 0x65, 0xf4, 0xc7,
	0x82, 0xfe, 0xb4, 0xe6, 0xbf, 0x6e, 0x45, 0x51, 0x92, 0x63, 0xe8, 0xfc, 0x32, 0x07, 0x6a, 0x0d,
	0xad, 0x51, 0xc0, 0x2a, 0x40, 0xde, 0x42, 0x6f, 0x95, 0x6d, 0x53, 0x5d, 0x94, 0x4b, 0xa9, 0x32,
	0x6a, 0xa3, 0x06, 0x35, 0x75, 0xa5, 0x32, 0xf2, 0x0e, 0x5c, 0x5d, 0xe6, 0x82, 0x3a, 0x43, 0x6b,
	0x34, 0x98, 0xbc, 0x18, 0xf3, 0x5c, 0x8e, 0xf1, 0xe2, 0x32, 0x29, 0x73, 0xc1, 0x50, 0x24, 0xef,
	0xc1, 0x53, 0xa5, 0xd2, 0x62, 0x43, 0xdd, 0x56, 0x59, 0x8c, 0x14, 0x96, 0xd5, 0x32, 0x79, 0x03,
	0x41, 0xce, 0x1f, 0xc4, 0x52, 0xc9, 0x47, 0x41, 0x3b, 0x43, 0x6b, 0xd4, 0x67, 0xbe, 0x21, 0x62,
	0xf9, 0x28, 0xc8, 0x29, 0x40, 0x25, 0x6a, 0x5e, 0x68, 0xea, 0xa1, 0x8a, 0xe5, 0xb1, 0x21, 0xa2,
	0x1f, 0x10, 0x36, 0x8e, 0x98, 0x50, 0x79, 0x96, 0x2a, 0xf3, 0xb0, 0xdf, 0xb8, 0xa7, 0xd6, 0xd0,
	0x19, 0xf5, 0x26, 0xbd, 0x56, 0x87, 0xec, 0x49, 0x24, 0xa7, 0xe0, 0x6e, 0x84, 0xe6, 0x68, 0xb0,
	0x37, 0x09, 0xb0, 0x68, 0x26, 0x34, 0x67, 0x48, 0x47, 0xdf, 0xc1, 0x35, 0xc8, 0x0c, 0x49, 0x67,
	0x9a, 0xaf, 0x71, 0x48, 0x7d, 0x56, 0x81, 0x83, 0xc6, 0xec, 0x83, 0xc6, 0xf6, 0x4d, 0x39, 0xfb,
	0xa6, 0xa2, 0xdf, 0x36, 0x78, 0x55, 0x37, 0x64, 0x00, 0xb6, 0xbc, 0xaf, 0x6f, 0xb6, 0xe5, 0x7d,
	0x6b, 0x6a, 0xf6, 0xff, 0xa7, 0xf6, 0xac, 0x1d, 0x9c, 0x80, 0xbf, 0xe2, 0xeb, 0xb5, 0x92, 0x0f,
	0x29, 0x6e, 0x21, 0x60, 0x4f, 0x98, 0x10, 0x70, 0x53, 0xbe, 0xa9, 0x26, 0x1e, 0x30, 0x3c, 0x13,
	0x0a, 0x5d, 0xb5, 0x2d, 0x90, 0xf6, 0x90, 0x6e, 0xa0, 0x51, 0xea, 0x00, 0xd0, 0x6e, 0xa5, 0xd4,
	0xf0, 0x30, 0x2d, 0xfe, 0x3f, 0x69, 0x39, 0x86, 0x8e, 0xd2, 0x5c, 0x0b, 0x1a, 0x54, 0x21, 0x43,
	0x60, 0x9e, 0x5f, 0x49, 0x5d, 0x52, 0xa8, 0x9e, 0x37, 0xe7, 0xb3, 0x31, 0xc0, 0xce, 0x29, 0x79,
	0x0d, 0x2f, 0xef, 0xe6, 0xd7, 0xf3, 0x9b, 0x6f, 0xf3, 0x65, 0xbc, 0x88, 0x93, 0xe9, 0x6c, 0x99,
	0x2c, 0x6e, 0xa7, 0xe1, 0x11, 0xe9, 0x82, 0x73, 0x31, 0x63, 0xa1, 0x75, 0xf6, 0x09, 0x60, 0x67,
	0xb9, 0x5d, 0x3f, 0x9d, 0x27, 0x57, 0xc9, 0xa2, 0x55, 0xff, 0xf9, 0x7c, 0x16, 0x5a, 0xa4, 0x0f,
	0x41, 0x72, 0xfe, 0xe5, 0xfa, 0x92, 0xdd, 0xdc, 0xdd, 0x86, 0xf6, 0xe4, 0x02, 0xfc, 0x26, 0x3c,
	0xe4, 0x23, 0x04, 0x97, 0x42, 0xd7, 0x4b, 0x21, 0xbb, 0x69, 0x36, 0x5f, 0xe5, 0xe4, 0xd5, 0x1e,
	0xd7, 0x84, 0x2d, 0x3a, 0xfa, 0xe9, 0xe1, 0x0f, 0xfb, 0xf0, 0x37, 0x00, 0x00, 0xff, 0xff, 0x47,
	0x8e, 0x0d, 0x40, 0x73, 0x03, 0x00, 0x00,
}
